import { notFound } from 'next/navigation';
import Link from 'next/link';
import ANSWERS from '@/data/answers.json';
import type { Metadata } from 'next';

// Static, citable answer pages for the canonical Center Study questions.
// Each was generated by the Ask pipeline (hybrid retrieval + verbatim-quote
// synthesis), reviewed by the owner before shipping, and is served as plain
// crawlable HTML with QAPage structured data — the format AI engines cite.

type Source = { slug: string; title: string; source: string };
type Answer = { question: string; answer: string; sources: Source[]; generatedAt: string };
const DATA = ANSWERS as Record<string, Answer>;

export function generateStaticParams() {
  return Object.keys(DATA).map((slug) => ({ slug }));
}
export const dynamicParams = false;

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const a = DATA[slug];
  if (!a) return {};
  const firstPara = a.answer.split('\n').find((l) => l.trim() && !l.startsWith('#')) || '';
  const description = firstPara.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').slice(0, 157).replace(/\s+\S*$/, '') + '…';
  return {
    title: a.question,
    description,
    alternates: { canonical: `https://center.study/ask/${slug}` },
  };
}

// ── Citation footnoting ──────────────────────────────────────────────────────
// The pipeline emits "quote" — [Post Title](/post/slug?q=…) after every quote.
// Repeating full titles inline is heavy; convert each to a superscript number
// (numbered per unique post, deep-linking to the exact passage) and collect
// the numbered source list rendered once at the bottom.
type Citation = { n: number; title: string; slug: string };
function footnoteCitations(md: string): { md: string; cites: Citation[] } {
  const bySlug = new Map<string, Citation>();
  // Only transform the answer body — the Excerpts section (after ---) keeps
  // its per-excerpt attribution, which is already a source listing.
  const cutAt = md.search(/\n---\n/);
  const body = cutAt === -1 ? md : md.slice(0, cutAt);
  const rest = cutAt === -1 ? '' : md.slice(cutAt);
  const out = body.replace(/\s*[—–]\s*\[([^\]]+)\]\((\/post\/[^)]+)\)/g, (_m, title: string, href: string) => {
    const slug = href.split('?')[0].replace('/post/', '');
    let c = bySlug.get(slug);
    if (!c) {
      c = { n: bySlug.size + 1, title, slug };
      bySlug.set(slug, c);
    }
    return `[^${c.n}](${href})`;
  });
  return { md: out + rest, cites: [...bySlug.values()] };
}

// ── Minimal markdown → JSX for the Ask output subset ────────────────────────
// (## headings, paragraphs, > blockquotes, --- rules, [text](href), **bold**,
// *italic*.) Server-rendered; no client runtime.

function inline(text: string, keyBase: string): React.ReactNode[] {
  const out: React.ReactNode[] = [];
  // links first, then emphasis inside remaining text
  const parts = text.split(/(\[[^\]]+\]\([^)]+\))/g);
  parts.forEach((part, i) => {
    // Footnote citation marker: superscript number deep-linking to the passage
    const fn = part.match(/^\[\^(\d+)\]\(([^)]+)\)$/);
    if (fn) {
      out.push(
        <sup key={`${keyBase}-${i}`} className="ml-0.5">
          <Link href={fn[2]} className="text-blue-600 dark:text-blue-400 no-underline hover:underline text-[0.72em] font-medium" title="View the passage in context">
            {fn[1]}
          </Link>
        </sup>
      );
      return;
    }
    const link = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
    if (link) {
      const href = link[2];
      const internal = href.startsWith('/');
      out.push(
        internal ? (
          <Link key={`${keyBase}-${i}`} href={href} className="text-blue-600 dark:text-blue-400 hover:underline">
            {link[1]}
          </Link>
        ) : (
          <a key={`${keyBase}-${i}`} href={href} className="text-blue-600 dark:text-blue-400 hover:underline" rel="noopener noreferrer">
            {link[1]}
          </a>
        )
      );
      return;
    }
    const em = part.split(/(\*\*[^*]+\*\*|\*[^*\n]+\*)/g);
    em.forEach((seg, j) => {
      if (!seg) return;
      const key = `${keyBase}-${i}-${j}`;
      if (seg.startsWith('**') && seg.endsWith('**') && seg.length > 4) out.push(<strong key={key}>{seg.slice(2, -2)}</strong>);
      else if (seg.startsWith('*') && seg.endsWith('*') && seg.length > 2) out.push(<em key={key}>{seg.slice(1, -1)}</em>);
      else out.push(seg);
    });
  });
  return out;
}

function renderAnswer(md: string): React.ReactNode[] {
  const blocks = md.split(/\n\n+/);
  return blocks.map((block, i) => {
    const b = block.trim();
    if (!b) return null;
    if (b === '---') return <hr key={i} className="border-gray-100 dark:border-gray-800 my-8" />;
    if (b.startsWith('## ')) {
      return (
        <h2 key={i} className="text-xl font-semibold mt-10 mb-4 text-gray-900 dark:text-white" style={{ fontFamily: 'var(--font-geist-sans, system-ui, sans-serif)' }}>
          {b.slice(3)}
        </h2>
      );
    }
    if (b.startsWith('> ')) {
      const quote = b.split('\n').map((l) => l.replace(/^>\s?/, '')).join(' ');
      return (
        <blockquote key={i} className="border-l-2 border-amber-600 dark:border-amber-500 pl-4 my-5">
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">{inline(quote, `q${i}`)}</p>
        </blockquote>
      );
    }
    // bold-title + link lines from the Excerpts section render as paragraphs
    return (
      <p key={i} className="my-4 leading-relaxed text-gray-800 dark:text-gray-200">
        {inline(b.replace(/\n/g, ' '), `p${i}`)}
      </p>
    );
  });
}

const SOURCE_LABELS: Record<string, string> = {
  substack: 'Substack', gablog: 'GABlog', book: 'Anthropomorphics', pdf: 'Essay',
  reddit: 'Thread', twitter: 'Thread', chronicle: 'Chronicle', ap: 'Anthropoetics',
};

export default async function AnswerPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const a = DATA[slug];
  if (!a) notFound();

  const { md: footnoted, cites } = footnoteCitations(a.answer);

  const textOnly = a.answer.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/[#>*]/g, '');
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'QAPage',
    mainEntity: {
      '@type': 'Question',
      name: a.question,
      answerCount: 1,
      acceptedAnswer: {
        '@type': 'Answer',
        text: textOnly.slice(0, 2500),
        url: `https://center.study/ask/${slug}`,
        author: { '@type': 'Organization', name: 'Center Study Center', url: 'https://center.study' },
      },
    },
  };

  const others = Object.entries(DATA).filter(([s]) => s !== slug).slice(0, 6);

  return (
    <main className="max-w-3xl w-full mx-auto px-4 pt-6 pb-24 sm:py-12">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} />

      <div className="mb-8">
        <Link href="/answers" className="text-sm text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300 transition-colors">
          ← All questions
        </Link>
        <p className="text-xs font-mono text-gray-400 dark:text-gray-500 uppercase tracking-widest mt-4 mb-1">
          Answered from the archive
        </p>
        <h1 className="text-2xl sm:text-3xl font-bold leading-tight text-gray-900 dark:text-white">
          {a.question}
        </h1>
        <p className="text-xs text-gray-400 dark:text-gray-500 mt-2">
          Synthesized from the corpus with verbatim citations · {a.generatedAt}
        </p>
      </div>

      <article style={{ fontFamily: 'var(--prose-font-family)', fontSize: '17px', lineHeight: 1.8 }}>
        {renderAnswer(footnoted)}
      </article>

      {cites.length > 0 && (
        <section className="mt-10 pt-6 border-t border-gray-100 dark:border-gray-800">
          <p className="text-xs font-mono uppercase tracking-widest text-gray-400 dark:text-gray-500 mb-3">Cited</p>
          <ol className="space-y-1.5">
            {cites.map((c) => (
              <li key={c.n} className="flex gap-2.5 text-sm">
                <span className="text-gray-400 dark:text-gray-500 tabular-nums flex-shrink-0 w-4 text-right">{c.n}.</span>
                <Link href={`/post/${c.slug}`} className="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 hover:underline transition-colors">
                  {c.title}
                </Link>
              </li>
            ))}
          </ol>
        </section>
      )}

      <section className="mt-10 pt-6 border-t border-gray-100 dark:border-gray-800">
        <div className="flex flex-wrap items-center gap-3">
          <Link
            href={`/ask?q=${encodeURIComponent(a.question)}`}
            className="px-4 py-2 rounded-xl bg-gray-900 dark:bg-white text-white dark:text-gray-900 text-sm font-semibold hover:opacity-90 transition-opacity"
          >
            Ask a follow-up →
          </Link>
          <Link href="/start" className="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200 transition-colors">
            New to Center Study? Start here
          </Link>
        </div>
      </section>

      {others.length > 0 && (
        <section className="mt-10">
          <p className="text-xs font-mono uppercase tracking-widest text-gray-400 dark:text-gray-500 mb-3">More questions</p>
          <div className="grid sm:grid-cols-2 gap-2">
            {others.map(([s, o]) => (
              <Link
                key={s}
                href={`/ask/${s}`}
                className="p-3 rounded-xl border border-gray-100 dark:border-gray-800 hover:border-gray-300 dark:hover:border-gray-600 text-sm text-gray-700 dark:text-gray-300 transition-colors"
              >
                {o.question}
              </Link>
            ))}
          </div>
        </section>
      )}
    </main>
  );
}
